# Generated by Django 3.2.13 on 2022-04-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('basketname', models.TextField()),
                ('foodname', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('status', models.TextField(default='unpaid')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Basket_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.TextField()),
                ('username', models.TextField()),
                ('basketname', models.TextField()),
                ('address', models.TextField()),
                ('item', models.TextField()),
                ('item_id', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('email', models.TextField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
